### ISSUE TITLE
Speed charts / stats not working for GPX 1.1 format

### ISSUE THREAD

**Issue by tneu33** [mendhak/gpsmapper#15]
While charts and stats showing distance or elevation work ok, they both fail to show speed, for example charts showing speed over distance or speed over time.

Attached is a screenshot of Samsung Galaxy S7, showing speed over time chart: empty chart, with no axis labels or graph.
![screenshot_20180922-211358_gpsmapper](https://user-images.githubusercontent.com/24492505/45920502-6ea92a80-bead-11e8-94ae-c3b6d2d7def9.jpg)
Stats showing speed result in other kind of empty display, having only the background image.

Attached is a zip file, containing a gpx file produced by the current version of Gpslogger, but the problem does not seem to be related to this spesific file.
[20180913-.zip](https://github.com/mendhak/gpsmapper/files/2408049/20180913-.zip)

The problem is quite old, I believe having met it first time over a year ago but I haven't reported it before. So it could be related to version released in January 2017. Over the time the Android version in my devices has changed from 7 to 8, but it seems to have no impact on this.

**Comment by mendhak** [comment]
Ah got it - this is related to GPX v 1.1 - the 1.1 format doesn't store speed.  So that means the parser would need to calculate the speed as it collects points.  I'll need a little time for this to figure out a decent approach but I think this can be done, though it may be unreliable.  In the meantime you can either ignore this particular chart or if you do want speed, use GPX v1.0 format.

**Comment by mendhak** [comment]
OK v12 is released
